import './globals.css';
import Link from 'next/link';

export const metadata = {
	title: 'Next.js App',
	description: 'Generated by cbd front',
};

export default function RootLayout({children}) {
	return (
		<html lang='en'>
			<body>
				<h1>
					<Link href='/'>Next.js</Link>
				</h1>

				<ul>
					<li>
						<Link href='/translate'>번역기</Link>
					</li>
					<li>
						<Link href='/notion'>노션</Link>
					</li>
					<li>
						<Link href='/map'>지도</Link>
					</li>
				</ul>
				{children}
			</body>
		</html>
	);
}
